# -*- coding: utf-8 -*-
"""TitanicVeriAnalizi.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17VOcV_8J28f7k35ES3SEGEzYqV6zN2ZN
"""

# Titanic veri seti import
import pandas as pd

# Kaggle'dan hazır Titanic dataseti
# https://www.kaggle.com/competitions/titanic/overview
url = 'https://raw.githubusercontent.com/datasciencedojo/datasets/master/titanic.csv'
df = pd.read_csv(url)

# Veriyi kontrol edelim
print("Veri seti başarıyla yüklendi")
print(f"Toplam satır sayısı: {len(df)}")
print(f"Toplam sütun sayısı: {len(df.columns)}")

# Verinin ilk 10 satırı
print("İlk 10 yolcu:")
print(df.head(10))

# Eksik veriler
print("Eksik veri sayıları:")
print(df.isnull().sum())

# Yaş sütunundaki eksik değerleri MEDYAN ile dolduruyoruz
# Medyan = ortadaki değer

yas_medyan = df['Age'].median()
print(f"Yaş medyanı: {yas_medyan}")

# Eksik yaşları medyan ile doldur
df['Age'].fillna(yas_medyan, inplace=True)

# Kontrol edelim
print(f"Yaş sütununda kalan eksik veri: {df['Age'].isnull().sum()}")

# Yaşları kategorize ettik
# 0-12 = Çocuk, 13-18 = Genç, 19-60 = Yetişkin, 60+ = Yaşlı

def yas_grubu(yas):
    if yas <= 12:
        return 'Çocuk'
    elif yas <= 18:
        return 'Genç'
    elif yas <= 60:
        return 'Yetişkin'
    else:
        return 'Yaşlı'

# Yeni sütun oluştur
df['Yas_Grubu'] = df['Age'].apply(yas_grubu)

# Kontrol
print(df[['Age', 'Yas_Grubu']].head(10))

# Cinsiyete göre hayatta kalma oranı
cinsiyet_analiz = df.groupby('Sex')['Survived'].agg(['sum', 'count', 'mean'])
cinsiyet_analiz.columns = ['Hayatta Kalan', 'Toplam', 'Oran']
cinsiyet_analiz['Yuzde'] = cinsiyet_analiz['Oran'] * 100

print("Cinsiyete Göre Hayatta Kalma:")
print(cinsiyet_analiz)

# Sınıfa göre hayatta kalma
sinif_analiz = df.groupby('Pclass')['Survived'].agg(['sum', 'count', 'mean'])
sinif_analiz.columns = ['Hayatta Kalan', 'Toplam', 'Oran']
sinif_analiz['Yuzde'] = sinif_analiz['Oran'] * 100

print("Sınıfa Göre Hayatta Kalma:")
print(sinif_analiz)

import seaborn as sns
import matplotlib.pyplot as plt

sns.set_style("whitegrid")
plt.figure(figsize=(10, 6))

# Cinsiyete göre hayatta kalma grafiği
sns.countplot(data=df, x='Sex', hue='Survived', palette='Set2')

# Grafik düzenlemeleri
plt.title('Cinsiyete Göre Hayatta Kalma Durumu', fontsize=16, fontweight='bold')
plt.xlabel('Cinsiyet', fontsize=12)
plt.ylabel('Kişi Sayısı', fontsize=12)
plt.legend(title='Survived', labels=['Öldü (0)', 'Hayatta Kaldı (1)'])
plt.tight_layout()

plt.show()

plt.figure(figsize=(10, 6))

# Sınıfa göre hayatta kalma
sns.countplot(data=df, x='Pclass', hue='Survived', palette='viridis')

plt.title('Sınıfa Göre Hayatta Kalma Durumu', fontsize=16, fontweight='bold')
plt.xlabel('Yolcu Sınıfı (1=En İyi) (3=En Kötü)', fontsize=12)
plt.ylabel('Kişi Sayısı', fontsize=12)
plt.legend(title='Survived', labels=['Öldü (0)', 'Hayatta Kaldı (1)'])
plt.tight_layout()

plt.show()

plt.figure(figsize=(10, 6))

# Boxplot
sns.boxplot(data=df, x='Pclass', y='Fare', palette='coolwarm')

plt.title('Sınıfa Göre Bilet Fiyatı Dağılımı', fontsize=16, fontweight='bold')
plt.xlabel('Yolcu Sınıfı', fontsize=12)
plt.ylabel('Bilet Ücreti ($)', fontsize=12)
plt.tight_layout()

plt.show()

# Yaş grubuna göre hayatta kalma
yas_grubu_analiz = df.groupby('Yas_Grubu')['Survived'].agg(['sum', 'count', 'mean'])
yas_grubu_analiz.columns = ['Hayatta Kalan', 'Toplam', 'Oran']
yas_grubu_analiz['Yuzde'] = yas_grubu_analiz['Oran'] * 100

print("Yaş Grubuna Göre Hayatta Kalma:")
print(yas_grubu_analiz)

# Görselleştir
plt.figure(figsize=(10, 6))
sns.barplot(data=df, x='Yas_Grubu', y='Survived',
            order=['Çocuk', 'Genç', 'Yetişkin', 'Yaşlı'],
            palette='mako', ci=None)

plt.title('Yaş Grubuna Göre Hayatta Kalma Oranı', fontsize=16, fontweight='bold')
plt.xlabel('Yaş Grubu', fontsize=12)
plt.ylabel('Hayatta Kalma Oranı', fontsize=12)
plt.tight_layout()

plt.show()

# Hem cinsiyete hem sınıfa göre
capraz_analiz = df.groupby(['Pclass', 'Sex'])['Survived'].mean() * 100
print("Sınıf ve Cinsiyete Göre Hayatta Kalma Yüzdesi:")
print(capraz_analiz)

# Isı haritası
pivot_table = df.pivot_table(values='Survived',
                               index='Pclass',
                               columns='Sex',
                               aggfunc='mean')

plt.figure(figsize=(8, 6))
sns.heatmap(pivot_table, annot=True, fmt='.2%', cmap='RdYlGn',
            cbar_kws={'label': 'Hayatta Kalma Oranı'})

plt.title('Sınıf ve Cinsiyete Göre Hayatta Kalma', fontsize=16, fontweight='bold')
plt.xlabel('Cinsiyet', fontsize=12)
plt.ylabel('Sınıf', fontsize=12)
plt.tight_layout()
plt.show()

# Sayısal sütunlar arasındaki ilişki
sayisal_sutunlar = ['Survived', 'Pclass', 'Age', 'SibSp', 'Parch', 'Fare']
korelasyon = df[sayisal_sutunlar].corr()

plt.figure(figsize=(10, 8))
sns.heatmap(korelasyon, annot=True, fmt='.2f', cmap='coolwarm',
            square=True, linewidths=1, cbar_kws={'label': 'Korelasyon'})

plt.title('Değişkenler Arası İlişki (Korelasyon Matrisi)', fontsize=16, fontweight='bold')
plt.tight_layout()

plt.show()

# Toplu Gösterimi
print("================================")
print("TİTANİC VERİ ANALİZİ - SON RAPOR")
print("================================")

print(f"\nGENEL İSTATİSTİKLER:")
print("--------------------")
print(f"Toplam Yolcu: {len(df)}")
print(f"Hayatta Kalan: {df['Survived'].sum()} (%{df['Survived'].mean()*100:.1f})")
print(f"Ölen: {len(df) - df['Survived'].sum()} (%{(1-df['Survived'].mean())*100:.1f})")

print(f"\nCİNSİYETE GÖRE:")
print("---------------")
for cinsiyet in ['male', 'female']:
    oran = df[df['Sex'] == cinsiyet]['Survived'].mean() * 100
    print(f"{cinsiyet.capitalize()}: %{oran:.1f} hayatta kaldı")

print(f"\nSINIFA GÖRE:")
print("------------")
for sinif in [1, 2, 3]:
    oran = df[df['Pclass'] == sinif]['Survived'].mean() * 100
    print(f"{sinif}. Sınıf: %{oran:.1f} hayatta kaldı")

print(f"\nYAŞ GRUBUNA GÖRE:")
print("-----------------")
for grup in ['Çocuk', 'Genç', 'Yetişkin', 'Yaşlı']:
    if grup in df['Yas_Grubu'].values:
        oran = df[df['Yas_Grubu'] == grup]['Survived'].mean() * 100
        print(f"{grup}: %{oran:.1f} hayatta kaldı")

print("\n" + "=================")
print("ANALİZ TAMAMLANDI")
print("=================")
